### ISSUE TITLE
projects triage

### ISSUE THREAD

**Issue by MartyLake** [abesto/gtd#4]
Hey,
I'm blocked at project triage with non-leaf project with tasks. I want to fix this.

Let's say I have a general projet `A` where I used to accumulate tasks, then started manual triage into `A.a, A.b, A.c, etc`.

How can I move all the tasks left to `A.misc` for example ? When I do `task pro:A`, it also returns tasks from `A.a, A.b, A.c, etc`.

**Comment by abesto** [comment]
Sorry for the horrible response time - as mentioned in the other issue, I forgot _again_ to set my own repo to watched.

So `pro:A`, like you noticed, filters for any project _starting with_ `A`. To get an exact match, use `task proj.is:A`:

```console
$ task add task-a proj:a
Created task 335.
The project 'a' has changed.  Project 'a' is 0% complete (1 task remaining).
$ task add task-a.1 proj:a.1
Created task 336.
The project 'a.1' has changed.  Project 'a.1' is 0% complete (1 task remaining).
$ task add task-a.2 proj:a.2
Created task 337.
The project 'a.2' has changed.  Project 'a.2' is 0% complete (1 task remaining).
$ task proj:a
[task next ( proj:a )]

ID  Age Project Description Urg
332 8s  a       task-a         1
333 6s  a.1     task-a.1       1
334 3s  a.2     task-a.2       1

3 tasks
$ task proj.is:a
[task next ( proj.is:a )]

ID  Age Project Description Urg
332 11s a       task-a         1

1 task
```

Closing this, but feel free to re-open if this is not a solution for some reason.
